
FAIL TrackEvent created with createEvent assert_throws: function "function () {
        var ev = document.createEvent('Trac..." did not throw(stack: assert@http://localhost:8800/resources/testharness.js:1738:42
assert_throws@http://localhost:8800/resources/testharness.js:583:19
http://localhost:8800/html/semantics/embedded-content/media-elements/interfaces/TrackEvent/createEvent.html:9:18
step@http://localhost:8800/resources/testharness.js:798:30
test@http://localhost:8800/resources/testharness.js:73:22
global code@http://localhost:8800/html/semantics/embedded-content/media-elements/interfaces/TrackEvent/createEvent.html:7:5)

