
FAIL just one argument assert_throws: function "function () {
    postMessage('');
  }" threw object "Error: SyntaxError: DOM Exception 12" that is not a DOMException NOT_SUPPORTED_ERR: property "code" is equal to 12, expected 9(stack: assert@http://localhost:8800/resources/testharness.js:1738:42
assert_throws@http://localhost:8800/resources/testharness.js:682:23
http://localhost:8800/webmessaging/without-ports/008.html:8:16
step@http://localhost:8800/resources/testharness.js:798:30
test@http://localhost:8800/resources/testharness.js:73:22
global code@http://localhost:8800/webmessaging/without-ports/008.html:7:5)

