
FAIL onerror, "not handled" with only window.onerror defined assert_unreached: Reached unreachable code(stack: assert@http://localhost:8800/resources/testharness.js:1738:42
assert_unreached@http://localhost:8800/resources/testharness.js:692:16
http://localhost:8800/workers/interfaces/WorkerGlobalScope/onerror/propagate-to-window-onerror.html:20:21
step@http://localhost:8800/resources/testharness.js:798:30
http://localhost:8800/resources/testharness.js:827:40)

